version: '3'
services:
  mysql_master:
    image: mysql_image:master
    user: root
    build:
      context: ./master 
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 13306:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.10
    container_name: mysql_master
    restart: always

  mysql_slave:
    image: mysql_image:slave
    build:
      context: ./slave 
      dockerfile: Dockerfile
    user: root
    stdin_open: true
    tty: true
    ports:
      - 13307:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.11
    depends_on: 
      - mysql_master
    container_name: mysql_slave      
    

networks:
  dock_net:
networks:
  dock_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/16
